### ISSUE TITLE
Change num_classes Error

### ISSUE THREAD

**Issue by wuyingxiong** [lkeab/gaussian-grouping#39]
Thanks for your work!

   In my understanding,**num_classes** represents the number of categories that classifier can  output,and 256 seems a little bit big.
   I only change the config/gaussian_dataset/train.json **num_classes** from 256 to 128,and run train script,which outputs some errors.How can I modify it?

  Hope for your reply!
```
output information follows:
Optimizing output/lerf/ramen
Output folder: output/lerf/ramen [04/06 16:04:42]
Reading camera 135/135 [04/06 16:04:42]
Loading Training Cameras [04/06 16:04:42]
Loading Test Cameras [04/06 16:04:49]
Number of points at initialisation :  30076 [04/06 16:04:49]
Num classes:  128 [04/06 16:04:50]
Training progress:   0%|                                  | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 312, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.use_wandb)
  File "train.py", line 106, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image)) + loss_obj
  File "/data_ssd/w50032615/code/gaussian-grouping-main/utils/loss_utils.py", line 46, in ssim
    window = window.cuda(img1.get_device())
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by gaoyuchen2000** [comment]
I had the same issue when I wanted to reduce the number to reduce memory consumption.
The answer to this question is the number of classes in this categorization is larger and you may print it out to check:
`        #print(f"Max label value: {gt_obj.max().item()}, Min label value: {gt_obj.min().item()}")
`
The max label value is 180 and min is 0, which means you have to have classes greater than or equal to181.
The solution I am trying is to hard squeeze it, (which is a dumb solution): 
e.g. 16classes:
`  gt_obj = (gt_obj.float() * (15 / 180)).long()
`
It results in much less accuracy, but find the classes reduced.
Please let me know if you have better idea, thanks.

**Comment by Matt-V50** [comment]
@lkeab Waiting for a better idea. I'd appreciate it if you could give us some advice.
