### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by ZhaoLongjiea** [lkeab/gaussian-grouping#48]
when I start to train this model and print "bash script/train.sh bear 1", then it occurs:

(3DSegment) lzha0538@gpu1-3w-1:~/segment/gaussian-grouping$ bash script/train.sh bear 1
Optimizing output/bear
Output folder: output/bear [31/07 17:19:21]
Reading camera 96/96 [31/07 17:19:21]
Loading Training Cameras [31/07 17:19:21]
Loading Test Cameras [31/07 17:19:23]
Number of points at initialisation :  63659 [31/07 17:19:23]
Num classes:  256 [31/07 17:19:23]
Training progress:   0%|                                                                                            | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 255, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.use_wandb)
  File "train.py", line 83, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/home/lzha0538/segment/gaussian-grouping/gaussian_renderer/__init__.py", line 95, in render
    cov3D_precomp = cov3D_precomp)
  File "/home/lzha0538/miniconda3/envs/3DSegment/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'sh_objs'
Training progress:   0%|                                                                                            | 0/30000 [00:00<?, ?it/s]
Looking for config file in output/bear/cfg_args
Config file found: output/bear/cfg_args
Rendering output/bear
Traceback (most recent call last):
  File "render.py", line 168, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test)
  File "render.py", line 135, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/home/lzha0538/segment/gaussian-grouping/scene/__init__.py", line 35, in __init__
    self.loaded_iter = searchForMaxIteration(os.path.join(self.model_path, "point_cloud"))
  File "/home/lzha0538/segment/gaussian-grouping/utils/system_utils.py", line 28, in searchForMaxIteration
    return max(saved_iters)
ValueError: max() arg is an empty sequence

**Comment by ZhaoLongjiea** [comment]
I found that the object_mask directory is essential for training. When I provide this directory, the error no longer occurs.

**Comment by xiao10ma** [comment]
@ZhaoLongjiea 可以问问你是如何解决的吗？我跟着作者的方法，下载了bear数据集，并放在了/data目录下。直接运行`bash train.sh`报错
```
  File "/data1/mazipei/gaussian-grouping/utils/system_utils.py", line 27, in searchForMaxIteration
    saved_iters = [int(fname.split("_")[-1]) for fname in os.listdir(folder)]
FileNotFoundError: [Errno 2] No such file or directory: 'output/bear/point_cloud'
```
我在想，为什么要从output目录下去加载呢？我明明还没有训练
